services:
  app:
    build:
      context: .
      target: development
    tty: true
    environment:
      DATABASE_USER: ${POSTGRES_USER:-qrstorage-user}
      DATABASE_USER_PASSWORD: ${POSTGRES_PASSWORD:-qrstorage-password}
      DATABASE_NAME: ${POSTGRES_DB:-qrstorage-dev}
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_SSL: "false"
      OBJECT_STORAGE_SCHEME: http
      OBJECT_STORAGE_PORT: 9000
      OBJECT_STORAGE_REGION: eu01
      OBJECT_STORAGE_USER: ${MINIO_USER:-minio-user}
      OBJECT_STORAGE_PASSWORD: ${MINIO_USER_PASSWORD:-minio-user-password}
      OBJECT_STORAGE_HOST: ${MINIO_HOST:-minio}
      OBJECT_STORAGE_BUCKET: qrstorage-dev
      QR_CODE_DEFAULT_LOCALE: "de"
      DEEPL_API_KEY: ""
      READSPEAKER_API_KEY: ""
      # Replace this in production with your own key!
      VAULT_ENCRYPTION_KEY_BASE64: "t+OOnuWntk0vLcMqnF8nyKp+EuKAK+FnUU8OpdN9RoA="
      # Please create a new secret for production runs:
      # - Use `mix phx.gen.secret` if you have elixir and phoenix installed
      # - Use `openssl rand -base64 64 | head -c 64` on a normal unix system
      # You can override this in `docker-compose.override.yml`
      SECRET_KEY_BASE: "this_secret_key_base_needs_to_have_a_length_of_at_least_64_characters_like_this_one!"
      URL_HOST: localhost
      URL_SCHEME: http
      URL_PORT: "4000"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - minio
    # Mount the lib and test folder to increase development speed (do not use for prod setups!)
    volumes:
      # You can override this in `docker-compose.override.yml`
      - ./:/app
      - /app/deps/
      - /app/assets/node_modules

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-qrstorage-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qrstorage-password}
      POSTGRES_DB: ${POSTGRES_DB:-qrstorage-dev}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # Exposing the port is not needed unless you want to access this database instance from the host.
    # Be careful when other postgres docker container are running on the same port
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-minio-user}
      - MINIO_ROOT_PASSWORD=${MINIO_USER_PASSWORD:-minio-user-password}
    volumes:
      - minio_data:/data
    ports:
      # this is for the admin console:
      - 9001:9001

volumes:
  minio_data:
  postgres_data:
